const supported_countries = {
  'at': {'country_name': 'Austria', 'data_years_from': '1947', 'data_years_to': '2019', 'who_country_code': 'AUT'},
  'au': {'country_name': 'Australia', 'data_years_from': '1921', 'data_years_to': '2020', 'who_country_code': 'AUS'},
  'by': {'country_name': 'Belarus', 'data_years_from': '1959', 'data_years_to': '2018', 'who_country_code': 'BLR'},
  'be': {'country_name': 'Belgium', 'data_years_from': '1841', 'data_years_to': '2022', 'who_country_code': 'BEL'},
  'bg': {'country_name': 'Bulgaria', 'data_years_from': '1947', 'data_years_to': '2021', 'who_country_code': 'BGR'},
  'ca': {'country_name': 'Canada', 'data_years_from': '1921', 'data_years_to': '2021', 'who_country_code': 'CAN'},
  'cl': {'country_name': 'Chile', 'data_years_from': '1992', 'data_years_to': '2020', 'who_country_code': 'CHL'},
  'hr': {'country_name': 'Croatia', 'data_years_from': '2001', 'data_years_to': '2020', 'who_country_code': 'HRV'},
  'cz': {'country_name': 'Czechia', 'data_years_from': '1950', 'data_years_to': '2021', 'who_country_code': 'CZE'},
  'fi': {'country_name': 'Finland', 'data_years_from': '1878', 'data_years_to': '2022', 'who_country_code': 'FIN'},
  'fr': {'country_name': 'France', 'data_years_from': '1816', 'data_years_to': '2021', 'who_country_code': 'FRA'},
  'de': {'country_name': 'Germany', 'data_years_from': '1990', 'data_years_to': '2020', 'who_country_code': 'DEU'},
  'gr': {'country_name': 'Greece', 'data_years_from': '1981', 'data_years_to': '2019', 'who_country_code': 'GRC'},
  'hk': {'country_name': 'Hong Kong', 'data_years_from': '1986', 'data_years_to': '2020', 'who_country_code': 'CHN'}, // no WHO code for HK, using China
  'hu': {'country_name': 'Hungary', 'data_years_from': '1950', 'data_years_to': '2020', 'who_country_code': 'HUN'},
  'is': {'country_name': 'Iceland', 'data_years_from': '1838', 'data_years_to': '2021', 'who_country_code': 'ISL'},
  'ie': {'country_name': 'Ireland', 'data_years_from': '1950', 'data_years_to': '2020', 'who_country_code': 'IRL'},
  'il': {'country_name': 'Israel', 'data_years_from': '1983', 'data_years_to': '2016', 'who_country_code': 'ISR'},
  'it': {'country_name': 'Italy', 'data_years_from': '1872', 'data_years_to': '2020', 'who_country_code': 'ITA'},
  'jp': {'country_name': 'Japan', 'data_years_from': '1947', 'data_years_to': '2021', 'who_country_code': 'JPN'},
  'lv': {'country_name': 'Latvia', 'data_years_from': '1959', 'data_years_to': '2019', 'who_country_code': 'LVA'},
  'lt': {'country_name': 'Lithuania', 'data_years_from': '1959', 'data_years_to': '2020', 'who_country_code': 'LTU'},
  'lu': {'country_name': 'Luxembourg', 'data_years_from': '1960', 'data_years_to': '2022', 'who_country_code': 'LUX'},
  'nl': {'country_name': 'Netherlands', 'data_years_from': '1850', 'data_years_to': '2021', 'who_country_code': 'NLD'},
  'nz': {'country_name': 'New Zealand', 'data_years_from': '1948', 'data_years_to': '2021', 'who_country_code': 'NZL'},
  'no': {'country_name': 'Norway', 'data_years_from': '1846', 'data_years_to': '2022', 'who_country_code': 'NOR'},
  'pl': {'country_name': 'Poland', 'data_years_from': '1958', 'data_years_to': '2019', 'who_country_code': 'POL'},
  'pt': {'country_name': 'Portugal', 'data_years_from': '1940', 'data_years_to': '2022', 'who_country_code': 'PRT'},
  'kr': {'country_name': 'Republic of Korea', 'data_years_from': '2003', 'data_years_to': '2020', 'who_country_code': 'KOR'},
  'ru': {'country_name': 'Russia', 'data_years_from': '1959', 'data_years_to': '2014', 'who_country_code': 'RUS'},
  'sk': {'country_name': 'Slovakia', 'data_years_from': '1950', 'data_years_to': '2019', 'who_country_code': 'SVK'},
  'si': {'country_name': 'Slovenia', 'data_years_from': '1983', 'data_years_to': '2019', 'who_country_code': 'SVN'},
  'es': {'country_name': 'Spain', 'data_years_from': '1908', 'data_years_to': '2021', 'who_country_code': 'ESP'},
  'se': {'country_name': 'Sweden', 'data_years_from': '1751', 'data_years_to': '2022', 'who_country_code': 'SWE'},
  'ch': {'country_name': 'Switzerland', 'data_years_from': '1876', 'data_years_to': '2022', 'who_country_code': 'CHE'},
  'tw': {'country_name': 'Taiwan', 'data_years_from': '1970', 'data_years_to': '2021', 'who_country_code': 'CHN'}, // no WHO code for TW, using China
  'ua': {'country_name': 'Ukraine', 'data_years_from': '1959', 'data_years_to': '2013', 'who_country_code': 'UKR'},
  'uk': {'country_name': 'United Kingdom', 'data_years_from': '1922', 'data_years_to': '2021', 'who_country_code': 'GBR'},
  'us': {'country_name': 'United States', 'data_years_from': '1933', 'data_years_to': '2021', 'who_country_code': 'USA'},
};

const who_map_age_to_groups = {
  0: 'Y0T1', 
  1: 'Y1T4', 2: 'Y1T4', 3: 'Y1T4', 4: 'Y1T4', 
  5: 'Y5T9', 6: 'Y5T9', 7: 'Y5T9', 8: 'Y5T9', 9: 'Y5T9', 
  10: 'Y10T14', 11: 'Y10T14', 12: 'Y10T14', 13: 'Y10T14', 14: 'Y10T14', 
  15: 'Y15T19', 16: 'Y15T19', 17: 'Y15T19', 18: 'Y15T19', 19: 'Y15T19', 
  20: 'Y20T24', 21: 'Y20T24', 22: 'Y20T24', 23: 'Y20T24', 24: 'Y20T24', 
  25: 'Y25T29', 26: 'Y25T29', 27: 'Y25T29', 28: 'Y25T29', 29: 'Y25T29', 
  30: 'Y30T34', 31: 'Y30T34', 32: 'Y30T34', 33: 'Y30T34', 34: 'Y30T34', 
  35: 'Y35T39', 36: 'Y35T39', 37: 'Y35T39', 38: 'Y35T39', 39: 'Y35T39', 
  40: 'Y40T44', 41: 'Y40T44', 42: 'Y40T44', 43: 'Y40T44', 44: 'Y40T44', 
  45: 'Y45T49', 46: 'Y45T49', 47: 'Y45T49', 48: 'Y45T49', 49: 'Y45T49', 
  50: 'Y50T54', 51: 'Y50T54', 52: 'Y50T54', 53: 'Y50T54', 54: 'Y50T54', 
  55: 'Y55T59', 56: 'Y55T59', 57: 'Y55T59', 58: 'Y55T59', 59: 'Y55T59', 
  60: 'Y60T64', 61: 'Y60T64', 62: 'Y60T64', 63: 'Y60T64', 64: 'Y60T64', 
  65: 'Y65T69', 66: 'Y65T69', 67: 'Y65T69', 68: 'Y65T69', 69: 'Y65T69', 
  70: 'Y70T74', 71: 'Y70T74', 72: 'Y70T74', 73: 'Y70T74', 74: 'Y70T74', 
  75: 'Y75T79', 76: 'Y75T79', 77: 'Y75T79', 78: 'Y75T79', 79: 'Y75T79', 
  80: 'Y80T84', 81: 'Y80T84', 82: 'Y80T84', 83: 'Y80T84', 84: 'Y80T84', 
  85: 'YGE_85', 86: 'YGE_85', 87: 'YGE_85', 88: 'YGE_85', 89: 'YGE_85', 
};

const who_causes_groups = ['Injuries',  'Chronic respiratory diseases', 'Cardiovascular diseases',  'Diabetes', 'Cancers', 'Other noncommunicable diseases',  'Maternal causes',  'Communicable diseases',  'Dimentias'];
const who_causes_colors = ['#0193d6',   '#892e2f',                      '#86bee7',                  '#ffe094',  '#023f88', '#f5887d',                         '#fcc513',          '#5e82a0',                'black'];
const who_sexes_map = {'m': 'MALE', 'f': 'FEMALE'};

const who_map_causes_to_groups = {
  'Ischaemic heart disease': 'Cardiovascular diseases',
  'Stroke': 'Cardiovascular diseases',
  'Trachea, bronchus, lung cancers': 'Cancers',
  'Chronic obstructive pulmonary disease': 'Chronic respiratory diseases',
  'Colon and rectum cancers': 'Cancers',
  'Prostate cancer': 'Cancers',
  'Stomach cancer': 'Cancers',
  'Pancreas cancer': 'Cancers',
  'Cirrhosis of the liver': 'Other noncommunicable diseases',
  'Lower respiratory infections': 'Communicable diseases',
  'Cardiomyopathy, myocarditis, endocarditis': 'Cardiovascular diseases',
  'Self-harm': 'Injuries',
  'Liver cancer': 'Cancers',
  'Bladder cancer': 'Cancers',
  'Mouth and oropharynx cancers': 'Cancers',
  'Hypertensive heart disease': 'Cardiovascular diseases',
  'Kidney cancer': 'Cancers',
  'Diabetes mellitus': 'Diabetes',
  'Oesophagus cancer': 'Cancers',
  'Alzheimer disease and other dementias': 'Dimentias',
  'Lymphomas, multiple myeloma': 'Other noncommunicable diseases',
  'Leukaemia': 'Cancers',
  'Alcohol use disorders': 'Other noncommunicable diseases',
  'Peptic ulcer disease': 'Other noncommunicable diseases',
  'Parkinson disease': 'Other noncommunicable diseases',
  'Larynx cancer': 'Cancers',
  'Falls': 'Injuries',
  'Kidney diseases': 'Other noncommunicable diseases',
  'Brain and nervous system cancers': 'Cancers',
  'Pancreatitis': 'Other noncommunicable diseases',
  'Melanoma and other skin cancers': 'Cancers',
  'Road injury': 'Injuries',
  'Gallbladder and biliary tract cancer': 'Cancers',
  'Fire, heat and hot substances': 'Injuries',
  'Gallbladder and biliary diseases': 'Other noncommunicable diseases',
  'Tuberculosis': 'Communicable diseases',
  'Poisonings': 'Injuries',
  'Drug use disorders': 'Other noncommunicable diseases',
  'Paralytic ileus and intestinal obstruction': 'Other noncommunicable diseases',
  'Drowning': 'Injuries',
  'Interpersonal violence': 'Injuries',
  'HIV/AIDS': 'Communicable diseases',
  'Asthma': 'Chronic respiratory diseases',
  'Skin diseases': 'Communicable diseases',
  'Rheumatic heart disease': 'Cardiovascular diseases',
  'Urolithiasis': 'Other noncommunicable diseases',
  'Exposure to mechanical forces': 'Injuries',
  'Thyroid cancer': 'Cancers',
  'Inflammatory bowel disease': 'Other noncommunicable diseases',
  'Mesothelioma': 'Cancers',
  'Meningitis': 'Сommunicable diseases',
  'Appendicitis': 'Other noncommunicable diseases',
  'Encephalitis': 'Communicable diseases',
  'Gastritis and duodenitis': 'Other noncommunicable diseases',
  'Epilepsy': 'Other noncommunicable diseases',
  'Rheumatoid arthritis': 'Other noncommunicable diseases',
  'Testicular cancer': 'Cancers',
  'Protein-energy malnutrition': 'Other noncommunicable diseases',
  'Multiple sclerosis': 'Other noncommunicable diseases',
  'Diarrhoeal diseases': 'Communicable diseases',
  'Echinococcosis': 'Communicable diseases',
  'Upper respiratory infections': 'Communicable diseases',
  'Collective violence and legal intervention': 'Injuries',
  'Acute hepatitis B': 'Communicable diseases',
  'Syphilis': 'Communicable diseases',
  'Rabies': 'Communicable diseases',
  'Cysticercosis': 'Communicable diseases',
  'Acute hepatitis E': 'Communicable diseases',
  'Tetanus': 'Communicable diseases',
  'Osteoarthritis': 'Other noncommunicable diseases',
  'Malaria': 'Communicable diseases',
  'Gout': 'Other noncommunicable diseases',
  'Back and neck pain': 'Other noncommunicable diseases',
  'Acute hepatitis A': 'Communicable diseases',
  'Acute hepatitis C': 'Communicable diseases',
  'Measles': 'Communicable diseases',
  'Genital herpes': 'Communicable diseases',
  'Whooping cough': 'Other noncommunicable diseases',
  'Diphtheria': 'Communicable diseases',
  'African trypanosomiasis': 'Communicable diseases',
  'Congenital anomalies': 'Other noncommunicable diseases',
  'Oral conditions': '',
  'Sudden infant death syndrome': 'Other noncommunicable diseases',
  'Benign prostatic hyperplasia': '',
  'Chagas disease': '',
  'Chlamydia': '',
  'Gonorrhoea': '',
  'Trichomoniasis': '',
  'Dengue': '',
  'Trachoma': '',
  'Yellow fever': '',
  'Natural disasters': '',
  'Infertility': 'Other noncommunicable diseases',
  'Gynecological diseases': '',
  'Migraine': 'Other noncommunicable diseases',
  'Non-migraine headache': 'Other noncommunicable diseases',
  'Glaucoma': 'Other noncommunicable diseases',
  'Cataracts': 'Other noncommunicable diseases',
  'Uncorrected refractive errors': 'Other noncommunicable diseases',
  'Macular degeneration': 'Other noncommunicable diseases',
  'Other vision loss': 'Other noncommunicable diseases',
  'Other hearing loss': 'Other noncommunicable diseases',
  'Iodine deficiency': 'Other noncommunicable diseases',
  'Vitamin A deficiency': 'Other noncommunicable diseases',
  'Iron-deficiency anaemia': 'Other noncommunicable diseases',
  'Breast cancer': 'Cancers',
  'Cervix uteri cancer': 'Cancers',
  'Corpus uteri cancer': 'Cancers',
  'Ovary cancer': 'Cancers',
  'Anxiety disorders': 'Other noncommunicable diseases',
  'Eating disorders': 'Other noncommunicable diseases',
  'Autism and Asperger syndrome': 'Other noncommunicable diseases',
  'Childhood behavioural disorders': 'Other noncommunicable diseases',
  'Idiopathic intellectual disability': 'Other noncommunicable diseases',
  'Thalassaemias': 'Other noncommunicable diseases',
  'Sickle cell disorders and trait': 'Other noncommunicable diseases',
  'Depressive disorders': 'Other noncommunicable diseases',
  'Bipolar disorder': 'Other noncommunicable diseases',
  'Schizophrenia': 'Other noncommunicable diseases',
  'Schistosomiasis': '',
  'Leishmaniasis': '',
  'Lymphatic filariasis': '',
  'Onchocerciasis': '',
  'Ascariasis': 'Communicable diseases',
  'Trichuriasis': 'Communicable diseases',
  'Hookworm disease': 'Communicable diseases',
  'Food-bourne trematodes': 'Communicable diseases',
  'Leprosy': 'Communicable diseases',
  'Otitis media': 'Other noncommunicable diseases',
  'Maternal conditions': 'Maternal causes',
  'Neonatal conditions': 'Communicable diseases',
};


const explanation_texts = {
  'cln':  'This is a clean canvas for a 101 years long Life&nbsp;Calendar made for printing and manual filling. It starts from a ring at the bottom left corner, from the first week of your life.',
  'lft':  'This is a 101 years long Life Calendar which is already pre-filled for a specified birthday. It starts from the circle at the bottom left corner, from the first week of life for a specified date of birth.',
  'mby':  'This is a 101 years long Life Calendar with 2 mortality charts built on it for a specified country, sex at birth and year of birth. Data source for these charts is <a href="https://www.mortality.org" target="_blank" title="Human Mortality Database">Human Mortality Database (HMD)</a>.',
  'mbly': 'This is a 101 years long Life Calendar with 4 mortality charts built on it for a specified country, sex at birth, year of birth and latest data-available year for that country. Data source for these charts is <a href="https://www.mortality.org" target="_blank" title="Human Mortality Database">Human Mortality Database (HMD)</a>.',
  'mc':   'This is a 101 years long Life Calendar with 4 mortality charts built on it for a specified country, sex at birth and "compare to" country and sex at birth both for the latest data-available years. Data source for these charts is <a href="https://www.mortality.org" target="_blank" title="Human Mortality Database">Human Mortality Database (HMD)</a>.',
  'all':  'This is a 101 years long Life Calendar which is already pre-filled for a specified birthday. It can have up to 6 mortality charts built on it for a specified country, sex at birth, year of birth, latest data-available year and "compare to" country and sex at birth for the latest data-available year. Data source for these charts is <a href="https://www.mortality.org" target="_blank" title="Human Mortality Database">Human Mortality Database (HMD)</a>.',
  'cau':  'This is a 89 years long "Causes of Deaths at age" stacked and normalized chart built for a specified country, sex at birth and latest data-available year. Data source for this chart is: <a href="https://www.who.int/data/gho/data/themes/mortality-and-global-health-estimates/ghe-leading-causes-of-death" target="_blank" title="The Global Health Observatory by World Health Organization">World Health Organization (WHO)</a>.',
  'cam':  'This is a 89 years long "Causes of Deaths at age" stacked and normalized chart shaped by a "Mortality at age" curve for a specified country, sex at birth and latest data-available year. Data sources for this chart are: <a href="https://www.mortality.org" target="_blank" title="Human Mortality Database">Human Mortality Database (HMD)</a> and <a href="https://www.who.int/data/gho/data/themes/mortality-and-global-health-estimates/ghe-leading-causes-of-death" target="_blank" title="The Global Health Observatory by World Health Organization">World Health Organization (WHO)</a>.',
  'cc':  'These are 89 years long "Causes of Deaths at age" stacked and normalized charts shaped by "Mortality at age" curves for a specified country and sex at birth vs. specified country to compare and sex at birth to compare at latest data-available year. Both charts are attached to the middle. Left half chart is horizontally flipped for better look & feel. Data sources for the charts are: <a href="https://www.mortality.org" target="_blank" title="Human Mortality Database">Human Mortality Database (HMD)</a> and <a href="https://www.who.int/data/gho/data/themes/mortality-and-global-health-estimates/ghe-leading-causes-of-death" target="_blank" title="The Global Health Observatory by World Health Organization">World Health Organization (WHO)</a>.',
}

const values_texts = {
  'cln':  'Lets you to print empty Life Calendar canvas, fill it manually with your favorite color(s) and then put it on a wall / fridge.',
  'lft':  'Shows you how many weeks have already passed since your birthday and allows you to print already pre-filled calendar instead of clean one.',
  'mby':  'Shows you mortality situation in your motherland for your sex at a year you were born. Explanatory data-skin.',
  'mbly': 'Shows you how mortality situation have changed in your motherland between your year of birth and latest data-available year. Explanatory data-skin.',
  'mc':   'Allows you to compare different countries and sexes &mdash; so you can see the difference in life expectancies in any combination: men with women in one country, women with women or men with men in different countries.',
  'all':  'Shows you how many weeks have already passed since your birthday and allows you to compare different countries and sexes &mdash; so you can see the difference in life expectancies in any combination: men with women in one country, women with women or men with men in different countries.',
  'cau':  'Shows you causes of deaths for the people of different sexes at different ages in different countries.',
  'cam':  'Shows you causes of deaths to understand the actual volumes of causes of deaths for the people of different sexes at different ages in different countries.',
  'cc':   'Allows you to compare causes of deaths for different countries and sexes &mdash; so you could see the relations of actual volumes of causes of deaths for the people of different sexes at different ages in different countries.',
}
